// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi4EOnlQcMOVmwmmES_zFHElLqcal1nmQ',
    appId: '1:232763023429:web:cc6a9cc5c72cef2aaf032c',
    messagingSenderId: '232763023429',
    projectId: 'biruninot-e44cb',
    authDomain: 'biruninot-e44cb.firebaseapp.com',
    storageBucket: 'biruninot-e44cb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1a3luPE4D0PFvDmEF4wnKpb4r_Pc3eU',
    appId: '1:232763023429:android:7b2b06d08a712d85af032c',
    messagingSenderId: '232763023429',
    projectId: 'biruninot-e44cb',
    storageBucket: 'biruninot-e44cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDM1nRQX9Z_bZACgFhZ--aucIKFJEFEcAI',
    appId: '1:232763023429:ios:eccf35a26f86f956af032c',
    messagingSenderId: '232763023429',
    projectId: 'biruninot-e44cb',
    storageBucket: 'biruninot-e44cb.appspot.com',
    iosBundleId: 'com.example.notkutusuapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDM1nRQX9Z_bZACgFhZ--aucIKFJEFEcAI',
    appId: '1:232763023429:ios:187adebb3f8fd82faf032c',
    messagingSenderId: '232763023429',
    projectId: 'biruninot-e44cb',
    storageBucket: 'biruninot-e44cb.appspot.com',
    iosBundleId: 'com.example.notkutusuapp.RunnerTests',
  );
}
